slack API token: TODO
user id: OPTIONAL_TODO
log level: INFO
check delay: 1
reply rules:
  - pattern: (?i)^(hello|hey|hi|yo+)( *yo+)*( justin)?[.!?]*$
    replies:
      - Hello. What can I help you with?
      - Hey. Do you need something?
      - Hey, how's it going?
      - Hi, what's up?
      - Yo. Is there anything that I can do for you?
      - Yo, what's up?
  - pattern: (?i)^good ?night[.!?]*$
    replies:
      - Smell you later.
      - Goodnight.
      - Have a good night.
